### ISSUE TITLE
git-wip currently unsuable for emacs users

### ISSUE THREAD

**Issue by expez** [bartman/git-wip#13]
Hi, git-wip is current unusable for emacs users.  It would be great if you could take a look at the issues list.  I think merging in the changes in #11 should do the trick as far as emacs support goes.

If you no longer want to maintain this tool you should consider giving someone else commit acces or even transfer ownership. It's too awesome to let die.  I'm sure some of the other committers would be willing to step up.

**Comment by neilmarion** [comment]
![12341516_1085197284833236_5440826715778313963_n](https://cloud.githubusercontent.com/assets/641821/11858609/fddbd518-a49d-11e5-8a01-a84b10c754bb.jpg)
